baseURL = "https://example.org/"
languageCode = "ja-JP"
title = "個人的な備忘録"
theme = "PaperMod"
paginate = 5


defaultContentLanguage = 'ja'

[minify]
disableXML = true
minifyOutput = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
env = "production"
title = "個人的な備忘録"
description = "色々やったことの覚書き。"
author = "三上五月"
defaultTheme = "auto"
dateFormat = "2006.01.02"
disableThemeToggle = false
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = false
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = true
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

[params.homeInfoParams]
Title = "個人的な備忘録"
Content = """
色々やったことの覚書き。<br>
作業環境：Win10, VSCode, CLIP STUDIO EX
"""

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[menu.main]]
name = "Search"
url = "search/"
weight = 10

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[[menu.main]]
name = "Home"
url = "https://mikamibox.com/"

[params.assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"
disableHLJS = true

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNos = false
style = "monokai"
